DELETE http://localhost:3001/api/blogs/67c2375613bc52b4b165d7c5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFndXN0aW5zb3NhLjEwIiwiaWQiOiI2N2MwODZjOWQyNjlkNGFlNzVkNzE1MTciLCJpYXQiOjE3NDEwOTkyMzIsImV4cCI6MTc0MTEwMjgzMn0.c1h8ILl9wXlQNFzPyl_m9BFKpoMRZOLYez5fmw1Gzgs